# Generated by Django 5.1.3 on 2024-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
