# Generated by Django 5.1.3 on 2024-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="dislike_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
