---

name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Print working directory
      run: pwd  # Prints the current directory

    - name: List files in the directory
      run: ls -alh  # List all files in the current directory

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
          
    - name: Run Migrations
      run: |
        source venv/bin/activate
        cd stayconnected
        python manage.py migrate
        
    - name: Check Gunicorn version
      run: |
        source venv/bin/activate
        gunicorn --version

    - name: Check if Gunicorn is running
      run: |
        ps aux | grep gunicorn

    - name: Restart Gunicorn
      run: |
        source venv/bin/activate
        sudo systemctl daemon-reload
        sudo systemctl restart gunicorn

