name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
          
    - name: Run Migrations
      run: |
        source venv/bin/activate
        cd stayconnected
        python manage.py migrate
        
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into server, pull latest code, and restart Gunicorn and Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.198.208.73 << 'EOF'
          echo "Pulling latest code..."
          cd /ubuntu/home/back-end
          echo "Stashing local changes (if any)..."
          git stash || true
          echo "Pulling latest changes from the repository..."
          git pull origin main || { echo "Git pull failed"; exit 1; }
          echo "Reapplying stashed changes (if any)..."
          git stash pop || true
          
          echo "Running migrations..."
          source venv/bin/activate
          python stayconnected/manage.py migrate

          echo "Restarting Gunicorn and Nginx..."
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
        EOF
      env:
        HOME: /home/ubuntu
